import Head from "next/head";
import { Header } from "../Components/Layouts/Header/Header";
import { Navbar } from "../Components/Layouts/Navbar/Navbar";
import { Results } from "../Components/Results/Results";
import request from "../utils/request";

export default function Home({ result }) {
  return (
    <div className="index">
      <Head>
        <title>Hulu Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Navbar />
      <Results results={result} />
    </div>
  );
}

export const getServerSideProps = async (context) => {
  const genre = context.query.genre;

  const requests = await fetch(
    `https://api.themoviedb.org/3${
      request[genre]?.url || request?.fetchTrending?.url
    }`
  ).then((res) => res.json());

  // https://api.themoviedb.org/3/movie/550?api_key=e1470daa0d537afda559eb3e1c706fd9
  return { props: { result: requests.results } };
};
